AllCops:
  Exclude:
    - './db/schema.rb'
    - './Gemfile'
    - './spec/stdout_example.rb'
    - './spec/factories.rb'
    - './db/seeds.rb'

  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 160

Documentation:
  Enabled: false

Rails:
  Enabled: true

Metrics/MethodLength:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 100
  Include:
    - './spec/*'

Metrics/AbcSize:
  Max: 20

Style/AsciiComments:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/HeredocDelimiterCase:
  Enabled: false