AllCops:
  Exclude:
    - './db/schema.rb'
    - './Gemfile'
    - './spec/stdout_example.rb'

  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 160

Documentation:
  Enabled: false

Rails:
  Enabled: true

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Metrics/BlockLength:
  Max: 100
  Include:
    - './spec/*'
