version: "3.2"
services:
  web:
    build: .
    command: rails s --binding 0.0.0.0
    volumes:
      - type: volume
        source: .
        target: /app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - OAUTH_SITE=https://tmc.mooc.fi
      - PORT=3000
      - DB_HOST=db
      - REDIS_PROVIDER=redis
    stdin_open: true
    tty: true
  db:
    image: postgres:alpine
    hostname: db
    cap_drop:
      - all
    cap_add:
      - chown
      - fowner
      - setuid
      - setgid
      - dac_override
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - type: volume
        source: .
        target: /app
    links:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - OAUTH_SITE=https://tmc.mooc.fi
      - DB_HOST=db
      - REDIS_PROVIDER=redis
