version: "3.2"
services:
  web:
    build: .
    command: rails s --binding 0.0.0.0
    volumes:
      - type: volume
        source: .
        target: /app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - RAILS_ENV=development
      - OAUTH_SITE=https://tmc.mooc.fi
      - PORT=3000
  db:
    image: postgres:alpine
    cap_drop:
      - all
    cap_add:
      - chown
      - fowner
      - setuid
      - setgid
      - dac_override
