development:
  adapter: redis
  url: redis://redis:6379

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: crowdsorcerer_production

#redis: &redis
#  adapter: redis
#  url: redis://localhost:6379/1
#
#production: *redis
#development: *redis
#test:
#  adapter: async